### ISSUE TITLE
What is .DS_STORE?

### ISSUE THREAD

**Issue by mccallum-sgd** [jackyyylewis/assign1#1]
@jackyyylewis
Not sure what [this file](https://github.com/jackyyylewis/assign1/blob/master/.DS_Store) is, was this an accident?

**Comment by jackyyylewis** [comment]
I'm not totally sure. It was a hidden file that I accidentally added. Not sure how it showed up when I pushed. And when I fetched the repository again it wasn't showing up so I couldn't delete it.

**Comment by jackyyylewis** [comment]
@mccallum-sgd I remember now.. I used "git add . " from force of habit and it added this file to the repository.

**Comment by mccallum-sgd** [comment]
@jackyyylewis 
Ah, I see. That's interesting. In the future I'd recommend checking with `git status` before you commit.

Fixed by [4704150](https://github.com/jackyyylewis/assign1/commit/470415046899f2b4982c6da864490c018a42edde)
